/// <reference path="../Refs/Xrm.Page.js" />
var NcIsProcessing = false;

var IsNcLoaded = window.IsNcLoaded || false;
var NcIsRegister = false;

var NcSettings = window.NcSettings;
var NcColours = window.NcColours;

var NcSliderLastCheckList = window.NcSliderLastCheckList || [];
var NcUnreadCount = window.NcUnreadCount || 0;
var NcLatestMinUnreadDate;
var NcLatestMenuOpenDate;

var NcSource =
{
	1: '/_imgs/ico_16_4402.gif',
	2: '/_imgs/ico_16_4202.gif',
	3: '/_imgs/ico_16_4212.gif',
	999: '/_imgs/ico_16_1152.gif'
};

var NcOutsideClickHandlers = [];

var NcReadMessages = [];
var NcReadMessagesQueue;

//#region Init

async function InitNotificationsMenu()
{
	try
	{
		if (NcIsProcessing || IsNcLoaded)
		{
			return false;
		}

		NcIsProcessing = true;

		NcReadMessagesQueue = new AsyncBlockingQueue();

		const isIconLoaded = $('#ncMainContainer').length;

		if (isIconLoaded)
		{
			NcIsProcessing = false;
			return false;
		}

		if (!NcSettings)
		{
			NcSettings =
			{
				IsEnabled: false,
				CountPerPage: 10,
				RefreshInterval: 5,
				IsPopupEnabled: true,
				PopupTimeout: 5
			};

			NcColours =
			{
				Main: '#BAE3FF',
				Links: '#0000FF'
			};

			const coloursPromise = FetchColours();

			await Promise.all([FetchConfiguration(), coloursPromise]);
		}

		if (!NcSettings.IsEnabled)
		{
			return false;
		}

		AddNotificationsIcon();
		NcIsRegister = true;

		NcIsProcessing = false;

		InitNc();
	}
	catch (e)
	{
		console.error('Notifications Centre => InitNotificationsMenu');
		console.error(e);
	}

	return false;
}

function AddNotificationsIcon()
{
	try
	{
		$('#navTabGroupDiv')
			.before('<span id="ncMainContainer" class="navTabButton">' +
				'<a href="#" class="navTabButtonLink" onkeypress="return true;" onclick="return false;" unselectable="on">' +
				'<span id="ncIcon" class="navTabButtonImageContainer" unselectable="on">' +
				'<img id="ncIconImage" src="' + Xrm.Page.context.getClientUrl() + '/WebResources/ldv_GlobePng52">' +
				'<span id="ncCounter" class="ncHiddenKeepSpace nc-counter-old"></span>' +
				//'<img id="ncQuickCreate" src="' + Xrm.Page.context.getClientUrl() + '/WebResources/ldv_PlusGreyIconPng25" />' +
				'</a>' +
				'<span id="ncTabDividerContainer" class="navTabButtonImageContainer" unselectable="on">' +
				'<img class="navTabDivider" alt="|" src="/_imgs/NavBar/NavBarDivider.png" unselectable="on">' +
				'</span>' +
				'</span>');

		
		$('div[data-id="topBar"]').children(":last").children(":first")
			.prepend('<div id="ncMainContainer" class="navTabButton nc-new">' +
				'<a href="#" class="navTabButtonLink" onkeypress="return true;" onclick="return false;" unselectable="on">' +
				'<span id="ncIcon" class="navTabButtonImageContainer" unselectable="on">' +
				'<img id="ncIconImage" src="' + Xrm.Page.context.getClientUrl() + '/WebResources/ldv_GlobePng52">' +
				'<span id="ncCounter" class="ncHiddenKeepSpace nc-counter"></span>' +
				//'<img id="ncQuickCreate" src="' + Xrm.Page.context.getClientUrl() + '/WebResources/ldv_PlusGreyIconPng25" />' +
				'</a>' +
				'</div>');
		$('#ncMainContainer').addClass($('[data-id="searchLauncher"]').attr('class'));
	}
	catch (e)
	{
		console.error('Notifications Centre => AddNotificationsIcon');
		console.error(e);
	}
}

async function FetchConfiguration()
{
	try
	{
		const a1 = $.ajax({
			type: "GET",
			contentType: "application/json; charset=utf-8",
			datatype: "json",
			url: Xrm.Page.context.getClientUrl() + "/api/data/v8.1/ldv_genericconfigurations" +
				"?$select=ldv_isnotificationscentreenabled",
			beforeSend: function(xmlHttpRequest)
			{
				xmlHttpRequest.setRequestHeader("OData-MaxVersion", "4.0");
				xmlHttpRequest.setRequestHeader("OData-Version", "4.0");
				xmlHttpRequest.setRequestHeader("Accept", "application/json");
			}
		});

		const userId = NcLibrary.GetUserId(true);

		const a2 = $.ajax({
			type: "GET",
			contentType: "application/json; charset=utf-8",
			datatype: "json",
			url: Xrm.Page.context.getClientUrl() + "/api/data/v8.1/ldv_notificationscentreconfigs" +
				"?$select=ldv_notificationscentreconfigid,ys_isautogenerated," +
				"ldv_countperpage,ldv_isdefault,ldv_ispopupenabled,ldv_popuptimeout," +
				"ldv_refreshinterval,_ownerid_value" +
				"&$filter=_ownerid_value eq " + userId + " or ldv_isdefault eq true",
			beforeSend: function(xmlHttpRequest)
			{
				xmlHttpRequest.setRequestHeader("OData-MaxVersion", "4.0");
				xmlHttpRequest.setRequestHeader("OData-Version", "4.0");
				xmlHttpRequest.setRequestHeader("Accept", "application/json");
			}
		});

		const [modConfigResult, userConfigResult] = await Promise.all([a1, a2]);

		const modConfig = modConfigResult.value;
		NcSettings.IsEnabled = (modConfig[0] ?? {})["ldv_isnotificationscentreenabled"] ?? false;

		const userConfig = userConfigResult.value;
		let config = (NcLibrary.Search(userConfig, 'ldv_isdefault', false, 1, true) ?? [])[0] ?? {};
		const defaultConfig = (NcLibrary.Search(userConfig, 'ldv_isdefault', true, 1, true) ?? [])[0] ?? {};

		NcSettings.Id = config["ldv_notificationscentreconfigid"];
		config = NcSettings.Id && config["ys_isautogenerated"] ? {} : config;

		NcSettings.CountPerPage = config["ldv_countperpage"] ?? defaultConfig["ldv_countperpage"]
			?? NcSettings.CountPerPage;
		NcSettings.RefreshInterval = config["ldv_refreshinterval"] ?? defaultConfig["ldv_refreshinterval"]
			?? NcSettings.RefreshInterval;
		NcSettings.IsPopupEnabled = config["ldv_ispopupenabled"] ?? defaultConfig["ldv_ispopupenabled"]
			?? NcSettings.IsPopupEnabled;
		NcSettings.PopupTimeout = config["ldv_popuptimeout"] ?? defaultConfig["ldv_popuptimeout"]
			?? NcSettings.PopupTimeout;

		if (!NcSettings.Id)
		{
			NcSettings.Id = (await Xrm.WebApi.online
				.createRecord("ldv_notificationscentreconfig",
					{
						"ys_isautogenerated": true,
						"ownerid@odata.bind": `/systemusers(${userId})`
					})).id;
		}
	}
	catch (e)
	{
		console.error('Notifications Centre => FetchConfiguration => Config Fetch');
		console.error(e);
	}
}

async function FetchColours()
{
	try
	{
		const results = await $.ajax({
			type: "GET",
			contentType: "application/json; charset=utf-8",
			datatype: "json",
			url: Xrm.Page.context.getClientUrl() + "/api/data/v8.1/themes" +
				"?$select=globallinkcolor,navbarbackgroundcolor" +
				"&$filter=isdefaulttheme eq true",
			beforeSend: function(xmlHttpRequest)
			{
				xmlHttpRequest.setRequestHeader("OData-MaxVersion", "4.0");
				xmlHttpRequest.setRequestHeader("OData-Version", "4.0");
				xmlHttpRequest.setRequestHeader("Accept", "application/json");
			}
		});

		const colours = (results.value ?? [])[0] ?? {};

		NcColours.Main = colours["navbarbackgroundcolor"] ?? NcColours.Main;
		NcColours.Links = colours["globallinkcolor"] ?? NcColours.Links;
	}
	catch (e)
	{
		console.error('Notifications Centre => FetchConfiguration => Generic Config Fetch');
		console.error(e);
	}
}

function InitNc()
{
	try
	{
		if (NcIsRegister)
		{
			NcIsRegister = false;
			CreatePalette();
			RegisterNcIconClick();

			if (!IsNcLoaded)
			{
				IsNcLoaded = true;
				InitRefreshInterval();
				NcStartCacheLoop();
			}
		}
	}
	catch (e)
	{
		console.error('Notifications Centre => ' + NcLibrary.GetFunctionName());
		console.error(e);
	}
}

function RegisterNcIconClick()
{
	$("#ncIcon")
		.click(function()
		{
			try
			{
				NcMenu().OpenMenu(this);
				NcLatestMenuOpenDate = new Date();
				CheckUnread();
			}
			catch (e)
			{
				console.error('Notifications Centre => RegisterNcIconClick => icon click');
				console.error(e);
			}
		});
}

function NcIsNew()
{
	return !!$('.nc-new').length;
}

function CreatePalette()
{
	try
	{
		NcColours.Unread = NcLibrary.shade(NcColours.Main, NcLibrary.IsDarkColour(NcColours.Main) ? 0.8 : 0.4);
		NcColours.Hover = NcLibrary.shade(NcColours.Main, NcLibrary.IsDarkColour(NcColours.Main) ? 0.95 : 0.65);
	}
	catch (e)
	{
		console.error('Notifications Centre => ' + NcLibrary.GetFunctionName());
		console.error(e);
	}
}

//#endregion

//#region Counter

function InitRefreshInterval()
{
	try
	{
		var loop = function()
		{
			setTimeout(function()
			{
				try
				{
					CheckUnread(NcSettings.IsPopupEnabled, loop);
				}
				catch (e)
				{
					console.error('Notifications Centre => InitRefreshInterval => loop timeout');
					console.error(e);
				}
			}, NcSettings.RefreshInterval * 1000);
		};

		loop();
		CheckUnread(false);
	}
	catch (e)
	{
		console.error('Notifications Centre => ' + NcLibrary.GetFunctionName());
		console.error(e);
	}
}

async function CheckUnread(isPopup, callback)
{
	try
	{
		const readPromise = await NcUpdateReadMessages();

		GetMessagesQuick(async function(messages)
		{
			try
			{
				await readPromise;
				const unreadMessages = messages.filter(e => !NcReadMessages.includes(e.id)
					&& (!NcLatestMenuOpenDate || new Date(e.date) > NcLatestMenuOpenDate));

				NcUnreadCount = unreadMessages.length;
				UpdateCounter();

				if (isPopup)
				{
					PopupUnread(unreadMessages);
				}

				NcLatestMinUnreadDate = new Date(Math.max.apply(null, messages.map(e => new Date(e.date))));
			}
			catch (e)
			{
				console.error('Notifications Centre => CheckUnread => GetMessagesQuick');
				console.error(e);
			}

			try
			{
				if (callback)
				{
					callback();
				}
			}
			catch (e)
			{
				console.error('Notifications Centre => CheckUnread => GetMessagesQuick => callback');
				console.error(e);
			}
		});
	}
	catch (e)
	{
		console.error('Notifications Centre => ' + NcLibrary.GetFunctionName());
		console.error(e);

		try
		{
			if (callback)
			{
				callback();
			}
		}
		catch (e)
		{
			console.error('Notifications Centre => CheckUnread => callback');
			console.error(e);
		}
	}
}

function UpdateCounter()
{
	try
	{
		var counterElement = $('#ncCounter');

		if (!counterElement.length)
		{
			return;
		}

		if (!NcUnreadCount)
		{
			counterElement.addClass('ncHiddenKeepSpace');
			return;
		}

		counterElement.removeClass('ncHiddenKeepSpace');

		var counterText = (NcUnreadCount > NcSettings.CountPerPage
							   ? NcSettings.CountPerPage
							   : NcUnreadCount) + '+';
		counterElement[0].innerHTML = counterText;
		//$('#ncIconImage').css('margin-right', (-10 + (counterText.toString().length * 7)) + 'px');
	}
	catch (e)
	{
		console.error('Notifications Centre => ' + NcLibrary.GetFunctionName());
		console.error(e);
	}
}

//#endregion

//#region Popup

function PopupUnread(unreadMessages)
{
	try
	{
		var popupBar = $('#ncPopupBar');

		if (!popupBar.length)
		{
			popupBar = $(
				'<div id="ncPopupBar" class="mainContainer">' +
				'<div id="ncPopupBarListContainer" style="position:relative;">' +
				'<div id="ncPopupBarList"></div>' +
				'</div>' +
				'</div>');
			$('body').append(popupBar);
			popupBar.hide();
		}

		var bar = $('#ncPopupBarList');
		var suffix = 'PopupBar';

		for (var i = 0; i < unreadMessages.length; i++)
		{
			if (!NcLatestMinUnreadDate || new Date(unreadMessages[i].date) > NcLatestMinUnreadDate)
			{
				GetMessage(unreadMessages[i].id, function(message)
				{
					try
					{
						var messageElement = BuildMessageElement(message, bar.width(), suffix);
						var separator = $('#dummy');

						if (popupBar.height() > 5)
						{
							separator = $('<hr id="separator_' + message.id + '_' + suffix + '" class="ncSeparator">');
						}

						bar.prepend(separator);
						bar.prepend(messageElement);
						messageElement.hide();
						messageElement.fadeIn(1000);
						popupBar.show();

						var timeout =
							setTimeout(function()
							{
								try
								{
									HidePopupMessage(message.id);
								}
								catch (e)
								{
									console.error('Notifications Centre => PopupUnread => GetMessage => timeout');
									console.error(e);
								}
							}, NcSettings.PopupTimeout * 1000);

						messageElement
							.click(function()
							{
								try
								{
									clearTimeout(timeout);
									HidePopupMessage(message.id, true);
								}
								catch (e)
								{
									console.error('Notifications Centre => PopupUnread => GetMessage => messageElement click');
									console.error(e);
								}
							});

						messageElement
							.hover(function()
							{
								try
								{
									clearTimeout(timeout);
								}
								catch (e)
								{
									console.error('Notifications Centre => PopupUnread => GetMessage => messageElement hover');
									console.error(e);
								}
							});
					}
					catch (e)
					{
						console.error('Notifications Centre => PopupUnread => GetMessage');
						console.error(e);
					}
				});
			}
		}

		if (unreadMessages.length)
		{
			NcLatestMinUnreadDate = new Date(unreadMessages[unreadMessages.length - 1].date);
		}
	}
	catch (e)
	{
		console.error('Notifications Centre => ' + NcLibrary.GetFunctionName());
		console.error(e);
	}
}

function HidePopupMessage(messageId, isInstantHide)
{
	try
	{
		var suffix = 'PopupBar';
		var timer = 5000;

		var message = $('#' + messageId + '_' + suffix);

		if (!message.length)
		{
			return;
		}

		var hide =
			function()
			{
				try
				{
					message.remove();
					$('#' + 'separator_' + messageId + '_' + suffix).remove();
					$('#' + 'hover_' + messageId + '_' + suffix).remove();
					$('#' + 'hover_undefined_' + suffix).remove();

					var popupBar = $('#ncPopupBar');

					if (popupBar.height() < 5)
					{
						popupBar.hide();
					}
				}
				catch (e)
				{
					console.error('Notifications Centre => HidePopupMessage => hide');
					console.error(e);
				}
			};

		if (isInstantHide)
		{
			hide();
			return;
		}

		message
			.hover(
				function()
				{
					try
					{
						$(this).stop().animate({ opacity: '1' });
					}
					catch (e)
					{
						console.error('Notifications Centre => HidePopupMessage => message hover');
						console.error(e);
					}
				});

		message.fadeTo(timer, '0.3', hide);
	}
	catch (e)
	{
		console.error('Notifications Centre => ' + NcLibrary.GetFunctionName());
		console.error(e);
	}
}

//#endregion

//#region Menu

var NcMenu = function()
{
	var ncFrame;
	var ncListContainer;
	var ncList;

	var isLoading;
	var isReachedEnd;

	var messagesList = [];
	var pagingInfo =
		{
			NextPage: 1,
			Count: NcSettings.CountPerPage,
			PagingCookie: null
		};

	function openMenu(buttonElement)
	{
		try
		{
			ncFrame = $('#ncFrame');

			if (ncFrame.length && $('#ncFrame').css('display') !== 'none')
			{
				CloseMenu(ncFrame);
				return;
			}

			drawMenu(buttonElement);
			showNextBatch();

			var image = $('#ncIconImage');
			image.stop(true);
			image.fadeTo(100, 0.30, function ()
			{
				try
				{
					image.attr('src', NcLibrary.GetOrgUrl() + '/WebResources/ldv_GlobeGlowPng52');
				}
				catch (e)
				{
					console.error('Notifications Centre => NcMenu => openMenu => fadeTo');
					console.error(e);
				}
			}).fadeTo(300, 1);
		}
		catch (e)
		{
			console.error('Notifications Centre => ' + NcLibrary.GetFunctionName());
			console.error(e);
		}
	}

	function drawMenu(buttonElement)
	{
		try
		{
			// credit: http://stackoverflow.com/a/158176/1919456
			var pos = $(buttonElement).position();
			ncFrame = $('<div id="ncFrame" class="ncNoLoading mainContainer arrow_box">' +
					'<div id="ncListContainer">' +
					'<div id="ncList"></div>' +
					'</div>' +
					'</div>')
				.css({
						top: pos.top + (NcIsNew() ? 29 : 62) + 'px',
						left: pos.left - 2 + 'px'
					});
			$('body').append(ncFrame);
			ncFrame.hide();

			ncListContainer = $('#ncListContainer');
			ncListContainer.perfectScrollbar();
			ncList = $('#ncList');

			var timeout;

			// on scroll to bottom, load new batch of messages
			// credit: http://stackoverflow.com/a/6271466/1919456
			ncListContainer.bind('scroll', function()
			{
				try
				{
					clearTimeout(timeout);
					var element = $(this);

					// use timeout to have the ability to clear others because sometimes this event is triggered twice
					timeout =
						setTimeout(function()
						{
							try
							{
								if (element.scrollTop() + element.innerHeight() + 0.5 >= element[0].scrollHeight)
								{
									showNextBatch();
								}
							}
							catch (e)
							{
								console.error('Notifications Centre => NcMenu => drawMenu => scroll => timeout');
								console.error(e);
							}
						}, 200);
				}
				catch (e)
				{
					console.error('Notifications Centre => NcMenu => drawMenu => scroll');
					console.error(e);
				}
			});

			var outsideClickHideHandler = function(event)
			{
				try
				{
					if (!$(event.target).closest('#ncFrame').length
						&& !$(event.target).closest('#ncIcon').length)
					{
						unregisterOutsideClick();
						CloseMenu(ncFrame);
					}
				}
				catch (e)
				{
					console.error('Notifications Centre => NcMenu => drawMenu => outsideClickHideHandler');
					console.error(e);
				}
			};

			$(window).on('mouseup', outsideClickHideHandler);
			NcOutsideClickHandlers.push({ window: window, handler: outsideClickHideHandler });
			registerOutsideClick($(document));

			ncFrame.prepend('<div id="ncTopBar">' +
				'<div id="ncNewIconContainer">' +
				'<a href="#" onkeypress="return true;" onclick="return false;">' +
				'<img id="ncNewIcon" src="' + Xrm.Page.context.getClientUrl() + '/WebResources/ldv_PlusGreyIconPng25" />' +
				'<div id="ncNewIconText"> Create New Notification</div>' +
				'</a>' +
				'</div>' +
				'</div>');

			registerNcQuickCreateClick();

			ncFrame.fadeIn(600);
		}
		catch (e)
		{
			console.error('Notifications Centre => ' + NcLibrary.GetFunctionName());
			console.error(e);
		}
	}

	function registerOutsideClick(element)
	{
		try
		{
			var iframes = $('iframe', element);
			iframes = iframes.length ? iframes : (element.length ? $('iframe', element.contents()) : []);

			var outsideClickHideHandler = function(event)
			{
				try
				{
					if (!$(event.target).closest('#ncFrame').length
						&& !$(event.target).closest('#ncIcon').length)
					{
						unregisterOutsideClick();
						CloseMenu(ncFrame);
					}
				}
				catch (e)
				{
					console.error('Notifications Centre => NcMenu => registerOutsideClick => outsideClickHideHandler');
					console.error(e);
				}
			};

			for (var i = 0; i < iframes.length; i++)
			{
				var contentWindow = iframes[i].contentWindow;

				if (contentWindow)
				{
					$(contentWindow).on('mouseup', outsideClickHideHandler);
					NcOutsideClickHandlers.push({ window: contentWindow, handler: outsideClickHideHandler });
				}

				registerOutsideClick($(iframes[i]));
			}
		}
		catch (e)
		{
			console.error('Notifications Centre => ' + NcLibrary.GetFunctionName());
			console.error(e);
		}
	}

	function unregisterOutsideClick()
	{
		try
		{
			for (const handlerPair of NcOutsideClickHandlers)
			{
				$(handlerPair.window).off('mouseup', handlerPair.handler);
			}

			NcOutsideClickHandlers = [];
		}
		catch (e)
		{
			console.error('Notifications Centre => ' + NcLibrary.GetFunctionName());
			console.error(e);
		}
	}

	function registerNcQuickCreateClick()
	{
		$("#ncNewIconContainer")
			.click(function(event)
			{
				try
				{
					openQuickCreate();
				}
				catch (e)
				{
					console.error('Notifications Centre => RegisterNcIconClick => icon click');
					console.error(e);
				}
			});
	}

	function openQuickCreate()
	{
		CloseMenu(ncFrame);

		Xrm.Utility.openQuickCreate('ldv_notificationmessage', null, null);

		setTimeout(function()
		{
			try
			{
				var formWindow = $('#NavBarGloablQuickCreate')[0].contentWindow;
				NcLibrary.LoadWebResources(['ldv_CommonGenericJs', 'ldv_CommonGenericSchemaJs', 'ldv_NotificationsCentreFormJs'],
					null, formWindow);
			}
			catch (e)
			{
				console.error('Notifications Centre => NcMenu => openQuickCreate => timeout');
				console.error(e);
			}
		}, 500);
	}

	function showNextBatch()
	{
		try
		{
			fetchMessages(false, function(newMessages)
			{
				try
				{
					updateMessagesList(false, newMessages);

					if (newMessages.length < pagingInfo.Count && !isReachedEnd)
					{
						showNextBatch();
					}
				}
				catch (e)
				{
					console.error('Notifications Centre => NcMenu => openMenu => fetchMessages');
					console.error(e);
				}
			});
		}
		catch (e)
		{
			console.error('Notifications Centre => ' + NcLibrary.GetFunctionName());
			console.error(e);
		}
	}

	function fetchMessages(isRefresh, callback)
	{
		try
		{
			// reached the end
			if (isLoading || isReachedEnd)
			{
				return;
			}

			setListLoading(true);

			var userId = NcLibrary.GetUserId();

			var parameters = {};
			var user = {};
			user.systemuserid = userId;
			user["@odata.type"] = "Microsoft.Dynamics.CRM.systemuser";
			parameters.User = user;
			parameters.Count = pagingInfo.Count;
			parameters.Page = isRefresh ? 1 : pagingInfo.NextPage++;
			parameters.Cookie = pagingInfo.PagingCookie;

			var loadFunction = function()
			{
				$.ajax({
						type: "POST",
						contentType: "application/json; charset=utf-8",
						datatype: "json",
						url: Xrm.Page.context.getClientUrl() + "/api/data/v8.1/ys_NotifyCentreGetMessages",
						data: JSON.stringify(parameters),
						beforeSend: function(xmlHttpRequest)
						{
							xmlHttpRequest.setRequestHeader("OData-MaxVersion", "4.0");
							xmlHttpRequest.setRequestHeader("OData-Version", "4.0");
							xmlHttpRequest.setRequestHeader("Accept", "application/json");
						},
						async: true,
						success: function(data, textStatus, xhr)
						{
							try
							{
								pagingInfo.PagingCookie = data.NewCookie;

								var results = JSON.parse((data.Messages).replace(/\\"/g, '\"'));
								var newMessages = [];

								for (var i = 0; i < results.length; i++)
								{
									var messageObject = results[i];
									messageObject.isRead = NcReadMessages.includes(messageObject.id);
									messageObject.regarding = messageObject.regarding || {};

									if (!NcLibrary.Contains(messagesList, null, messageObject.id))
									{
										newMessages.push(messageObject);
										messagesList.push(messageObject.id);
									}
								}

								isReachedEnd = data.IsReadEnd;

								if (callback)
								{
									callback(newMessages);
								}
							}
							catch (e)
							{
								console.error('Notifications Centre => NcMenu => fetchMessages => ajax');
								console.error(e);
							}
							finally
							{
								setListLoading(false);
							}
						},
						error: function(xhr, textStatus, errorThrown)
						{
							try
							{
								pagingInfo.NextPage--;
								setListLoading(false);
								console.error(xhr);
							}
							catch (e)
							{
								console.error('Notifications Centre => NcMenu => fetchMessages => ajax error');
								console.error(e);
							}
						}
					});
			};

			// delay loading a bit to give the UI a chance to draw
			// start from '2' because it was incremented above
			if (pagingInfo.NextPage === 2)
			{
				setTimeout(loadFunction, 300);
			}
			else
			{
				loadFunction();
			}
		}
		catch (e)
		{
			console.error('Notifications Centre => ' + NcLibrary.GetFunctionName());
			console.error(e);
		}
	}

	function setListLoading(isLoadingLocal)
	{
		try
		{
			isLoading = isLoadingLocal;

			if (isLoadingLocal)
			{
				ncListContainer.append(
					'<div id="ncLoadingDiv">' +
					'<img src="' + NcLibrary.GetOrgUrl() + '/WebResources/ldv_SmoothLoadingGif20" />' +
					'<div>');
				ncListContainer.scrollTop(ncListContainer[0].scrollHeight);
			}
			else
			{
				$('#ncLoadingDiv').remove();
			}
		}
		catch (e)
		{
			console.error('Notifications Centre => ' + NcLibrary.GetFunctionName());
			console.error(e);
		}
	}

	function updateMessagesList(isNew, newMessages)
	{
		try
		{
			for (var i = 0; i < newMessages.length; i++)
			{
				addMessageToList(newMessages[i], isNew);

				var listDimensions = NcLibrary.GetElementDimensions(ncList, ncFrame.width(), $);
				ncListContainer.height(Math.min(listDimensions[1] - 5, 400));
			}

			if (ncListContainer.scrollTop() > 5)
			{
				ncListContainer.scrollTop(ncListContainer.scrollTop() - 5);
			}

			ncListContainer.perfectScrollbar('update');
		}
		catch (e)
		{
			console.error('Notifications Centre => ' + NcLibrary.GetFunctionName());
			console.error(e);
		}
	}

	function addMessageToList(message, isAddTop)
	{
		try
		{
			var messageElement = BuildMessageElement(message, ncList.width(), '');

			if (isAddTop)
			{
				ncList.prepend(messageElement);
			}
			else
			{
				ncList.append(messageElement);
			}

			messageElement.after('<hr class="ncSeparator">');
		}
		catch (e)
		{
			console.error('Notifications Centre => ' + NcLibrary.GetFunctionName());
			console.error(e);
		}
	}

	return { OpenMenu: openMenu };
};

function CloseMenu(ncFrame)
{
	try
	{
		ncFrame.remove();

		var image = $('#ncIconImage');
		image.stop(true);
		image.fadeTo(100, 0.30, function ()
		{
			try
			{
				image.attr('src', NcLibrary.GetOrgUrl() + '/WebResources/ldv_GlobePng52');
			}
			catch (e)
			{
				console.error('Notifications Centre => CloseMenu => fadeTo');
				console.error(e);
			}
		}).fadeTo(300, 1);
	}
	catch (e)
	{
		console.error('Notifications Centre => ' + NcLibrary.GetFunctionName());
		console.error(e);
	}
}

//#endregion

//#region Messages

function BuildMessageElement(message, width, suffix)
{
	try
	{
		var regardingUrl = message.regarding.id
							   ? (NcLibrary.GetOrgUrl() + '/main.aspx?etc=' + message.regarding.typecode +
								   '&id=%7b' + message.regarding.id + '%7d' + '&newWindow=true&pagetype=entityrecord')
							   : '';

		var messageElement = $('<div id="' + message.id + '_' + suffix + '" messageRead="' + message.isRead +
			'" class="ncMessageContainer">' +
			'</div>');
		//.toggleClass('ncMessageUnread', !message.isRead);
		messageElement.css('background-color', message.isRead ? '' : NcColours.Unread);

		messageElement
			.hover(function()
				{
					//$(this).addClass('ncMessageHover');
					$(this).css('background-color', NcColours.Hover);
				},
				function()
				{
					try
					{
						// change back the colour of message
						var element = $(this);
						//element.removeClass('ncMessageHover');
						element.css('background-color', '');
						//element.toggleClass('ncMessageUnread', element.attr('messageRead') !== 'true');
						element.css('background-color', element.attr('messageRead') === 'true' ? '' : NcColours.Unread);
					}
					catch (e)
					{
						console.error('Notifications Centre => BuildMessageElement => messageElement hover');
						console.error(e);
					}
				});

		var sourceImage = NcSource[message.source];

		var titleElement = $('<div style="position:relative;">' +
			(sourceImage ? '<img class="ncSourceIcon" src="' + NcSource[message.source] + '" />' : '') +
			'<div style="width:' + (width - 45) + `px;" class="ncMessageTitle${NcIsNew() ? '' : '-old'} ncEllipsis" ` +
			`title="${message.title}">` +
			message.title +
			'</div>' +
			'</div>');

		var readAnchorElement = $('#dummyElement');
		
		if (!message.isRead)
		{
			readAnchorElement = $('<div id="read_' + message.id + '_' + suffix + '" class="ncReadIcon">' +
					'<a href="#" onkeypress="return true;" onclick="return false;">' +
					'<img src="' + NcLibrary.GetOrgUrl() + '/WebResources/ldv_ReadIconPng15" />' +
					'</a>' +
					'</div>')
				.click(function()
				{
					try
					{
						SetMessageRead($(this), messageElement, message.id);
					}
					catch (e)
					{
						console.error('Notifications Centre => BuildMessageElement => readAnchorElement click');
						console.error(e);
					}
				})
				.hover(function()
					{
						try
						{
							var element = $('img:eq(0)', this);
							element.attr('src', NcLibrary.GetOrgUrl() + '/WebResources/ldv_ReadHighlightPng15');
						}
						catch (e)
						{
							console.error('Notifications Centre => BuildMessageElement => readAnchorElement hover');
							console.error(e);
						}
					},
					function()
					{
						try
						{
							var element = $('img:eq(0)', this);
							element.attr('src', NcLibrary.GetOrgUrl() + '/WebResources/ldv_ReadIconPng15');
						}
						catch (e)
						{
							console.error('Notifications Centre => BuildMessageElement => readAnchorElement hover');
							console.error(e);
						}
					});

			titleElement.append(readAnchorElement);
		}

		const messageEscaped = message.message.replace(/\\r\\n/ig, '<br />');

		var bodyElement = $(`<div class="${NcIsNew() ? 'nc-message-body ' : ''}ncEllipsis" ` +
			`title="${messageEscaped.replace(/<br \/>/ig, '')}">` +
			(NcLibrary.IsHtml(messageEscaped)
				 ? '(Message in HTML format; hover to view)'
				 : messageEscaped) +
			'</div>');

		var urlElement = $('<span>&nbsp;</span>');

		if (regardingUrl)
		{
			urlElement = $('<div style="width:' + (width / 2) + 'px;" class="ncEllipsis"></div>');
			var url = $('<a href="' + regardingUrl + '" target="_blank" style="text-decoration:underline;">'
				+ message.regarding.name + '</a>');
			url.css('color', NcColours.Links);
			urlElement.append(url);

			urlElement
				.click(function()
				{
					try
					{
						if (messageElement.attr('messageRead') === "false")
						{
							SetMessageRead(readAnchorElement, messageElement, message.id);
						}
					}
					catch (e)
					{
						console.error('Notifications Centre => BuildMessageElement => urlElement click');
						console.error(e);
					}
				});
		}

		var footerElement = $('<div style="position:relative;">' +
			'<div class="ncDate">' + message.modifiedonString + '</div>' +
			'</div>');

		footerElement.prepend(urlElement);

		messageElement
			.append(titleElement)
			.append(bodyElement)
			.append(footerElement);

		return messageElement;
	}
	catch (e)
	{
		console.error('Notifications Centre => ' + NcLibrary.GetFunctionName());
		console.error(e);
		return $('#dummy');
	}
}

function GetMessagesQuick(callback)
{
	try
	{
		var userId = NcLibrary.GetUserId();

		var parameters = {};
		var user = {};
		user.systemuserid = userId;
		user["@odata.type"] = "Microsoft.Dynamics.CRM.systemuser";
		parameters.User = user;
		parameters.Count = NcSettings.CountPerPage;

		$.ajax({
				type: "POST",
				contentType: "application/json; charset=utf-8",
				datatype: "json",
				url: Xrm.Page.context.getClientUrl() + "/api/data/v8.1/ys_NotifyCentreGetMessages",
				data: JSON.stringify(parameters),
				beforeSend: function(xmlHttpRequest)
				{
					xmlHttpRequest.setRequestHeader("OData-MaxVersion", "4.0");
					xmlHttpRequest.setRequestHeader("OData-Version", "4.0");
					xmlHttpRequest.setRequestHeader("Accept", "application/json");
				},
				async: true,
				success: function(data, textStatus, xhr)
				{
					try
					{
						var results = JSON.parse((data.Messages).replace(/\\"/g, '\"'));
						var messages = $.map(results,
							function(e)
							{
								return { id: e.id, date: e.modifiedon };
							});

						if (callback)
						{
							callback(messages);
						}
					}
					catch (e)
					{
						console.error('Notifications Centre => NcMenu => GetUnreadMessages => ajax');
						console.error(e);

						if (callback)
						{
							callback([]);
						}
					}
				},
				error: function(xhr, textStatus, errorThrown)
				{
					console.error('Notifications Centre => NcMenu => GetUnreadMessages => ajax');
					console.error(xhr);

					if (callback)
					{
						callback([]);
					}
				}
			});
	}
	catch (e)
	{
		console.error('Notifications Centre => ' + NcLibrary.GetFunctionName());
		console.error(e);

		if (callback)
		{
			callback([]);
		}
	}
}

function GetMessage(id, callback)
{
	try
	{
		var parameters = {};
		parameters.MessageId = id;

		$.ajax({
			type: "POST",
			contentType: "application/json; charset=utf-8",
			datatype: "json",
			url: Xrm.Page.context.getClientUrl() + "/api/data/v8.1/ys_NotifyCentreGetMessages",
			data: JSON.stringify(parameters),
			beforeSend: function (xmlHttpRequest)
			{
				xmlHttpRequest.setRequestHeader("OData-MaxVersion", "4.0");
				xmlHttpRequest.setRequestHeader("OData-Version", "4.0");
				xmlHttpRequest.setRequestHeader("Accept", "application/json");
			},
			async: true,
			success: function(data, textStatus, xhr)
			{
				try
				{
					var message = JSON.parse((data.Messages).replace(/\\"/g, '\"'))[0];
					
					if (message)
					{
						if (callback)
						{
							message.regarding = message.regarding || {};
							message.isRead = false;
							callback(message);
						}
					}
				}
				catch (e)
				{
					console.error('Notifications Centre => GetMessage => ajax => success');
					console.error(e);
				}
			},
			error: function (xhr, textStatus, errorThrown)
			{
				console.error('Notifications Centre => GetMessage => ajax => error');
				console.error(xhr);
			}
		});
	}
	catch (e)
	{
		console.error('Notifications Centre => ' + NcLibrary.GetFunctionName());
		console.error(e);
	}
}

function SetMessageRead(readAnchorElement, messageElement, messageid)
{
	try
	{
		readAnchorElement.hide();
		messageElement.css('background-color', '');
		//messageElement.removeClass('ncMessageUnread');
		messageElement.attr('messageRead', 'true');

		NcUnreadCount--;
		UpdateCounter();

		NcReadMessages.push(messageid);
		NcReadMessagesQueue.enqueue(messageid);
	}
	catch (e)
	{
		console.error('Notifications Centre => ' + NcLibrary.GetFunctionName());
		console.error(e);

		NcUnreadCount++;
		UpdateCounter();

		readAnchorElement.show();
		//messageElement.addClass('ncMessageUnread');
		messageElement.css('background-color', NcColours.Unread);
		messageElement.attr('messageRead', 'false');
	}
}

//#endregion

//#region Cache

async function NcStartCacheLoop()
{
	while (true)
	{
		try
		{
			await NcReadMessagesQueue.dequeue();
			await NcSaveCache();
		}
		catch (e)
		{
			console.error('Notifications Centre => NcStartCacheLoop', e);
		} 
	}
}

async function NcUpdateReadMessages()
{
	const readCache = await Xrm.WebApi.online
		.retrieveMultipleRecords("ldv_notificationscentreconfig",
			`?$select=ys_readmessagescache&$filter=ldv_notificationscentreconfigid eq ${NcSettings.Id}`);
	NcReadMessages = NcConsolidateArrays(NcParseReadCacheRaw(readCache), NcReadMessages);
}

function NcParseReadCacheRaw(readCache)
{
	return JSON.parse((((readCache && readCache.entities) || [])[0] ?? {}).ys_readmessagescache ?? '[]');
}

async function NcSaveCache()
{
	if (!NcReadMessages.length)
	{
		return;
	}

	await NcUpdateReadMessages();

	const record =
	{
		ys_readmessagescache: JSON.stringify(NcReadMessages ?? [])
	};

	await Xrm.WebApi.online.updateRecord("ldv_notificationscentreconfig", NcSettings.Id, record);
}

//#endregion

//#region Helpers

function NcConsolidateArrays(array1, array2)
{
	return [...new Set([...array1, ...array2])];
}

function GetValueFromLocalStorage(key)
{
	return JSON.parse((localStorage.getItem(key)).replace(/\\"/g, '\"'));
}

function StoreValueInLocalStorage(key, value)
{
	localStorage.setItem(key, JSON.stringify(value));
}

//#endregion

// credit: Bergi (https://www.py4u.net/discuss/280744)
class AsyncBlockingQueue {
	constructor()
	{
		this.resolvers = [];
		this.promises = [];
	}

	_add()
	{
		this.promises.push(new Promise(resolve =>
		{
			this.resolvers.push(resolve);
		}));
	}

	enqueue(t)
	{
		if (!this.resolvers.length)
			this._add();
		this.resolvers.shift()(t);
	}

	dequeue()
	{
		if (!this.promises.length)
			this._add();
		return this.promises.shift();
	}

	isEmpty()
	{
		return !this.promises.length;
	}

	isBlocked()
	{
		return !!this.resolvers.length;
	}

	get length()
	{
		return this.promises.length - this.resolvers.length;
	}

	[Symbol.asyncIterator]()
	{
		return {
			next: () => this.dequeue().then(value => ({ done: false, value }))
		};
	}
}

InitNotificationsMenu();
