#region Imports

using System;
using System.Linq;
using System.Xml;
using Microsoft.Xrm.Sdk;
using Yagasoft.Libraries.Common;

#endregion

namespace Yagasoft.NotificationCentre.Plugins.Flags
{
	/// <summary>
	///     Resets 'auto-generated' flag upon manual update.<br />
	///     Version: 1.1.1
	/// </summary>
	public class ResetAutoGeneratedFlag : IPlugin
	{
		public void Execute(IServiceProvider serviceProvider)
		{
			new ResetAutoGeneratedFlagLogic().Execute(this, serviceProvider);
		}
	}

	internal class ResetAutoGeneratedFlagLogic : PluginLogic<ResetAutoGeneratedFlag>
	{
		public ResetAutoGeneratedFlagLogic() : base("Update", PluginStage.PreOperation, NotificationsCentreConfig.EntityLogicalName)
		{ }

		protected override void ExecuteLogic()
		{
			// get the triggering record
			var target = Target.ToEntity<NotificationsCentreConfig>();

			if (!target.Attributes.Contains(NotificationsCentreConfig.Fields.ReadMessagesCache))
			{
				target.AutoGenerated = false;
			}
		}
	}
}
